### ISSUE TITLE
Unable to detect duplicate accounts

### ISSUE THREAD

**Issue by Chocological** [CS2113-AY1819S1-F09-1/main#24]
Unable to detect duplicate user ID when creating new account.
Some tests failing.
issue: in XmlSerializableLoginBookTest -> toModelType_duplicateAccounts_throwsIllegalValueException() -> IllegalValueException not thrown when it is expected to be thrown when there are duplicates
what i think may be causing the problem: logic errors in various(?) Xml classes for login book in storage component

What i do know now: logic for detecting duplicate user ID is okay (isSameAccount() method), there may be issues correctly quering existing accounts
from storage component (Storage -> Model issue)

issue in tests: in XmlSerializableLoginBookTest -> toModelType_typicalAccountsFile_success() -> AssertionError -> 
Expected :seedu.address.model.LoginBook<4 accounts> 
Actual   :seedu.address.model.LoginBook<4 accounts>
Note: There is a whitespace at the end of expected result whereas there isn't any at the end of actual result

issue in tests: in XmlLoginBookStorageTest -> readAndSaveLoginBook_allInOrder_success() -> AssertionError -> 
Expected :seedu.address.model.LoginBook<4 accounts> 
Actual   :seedu.address.model.LoginBook<4 accounts>
Note: There is a whitespace at the end of expected result whereas there isn't any at the end of actual result

issue in tests: in XmlAccountTest -> toModelType_validAccountDetails_returnsAccount() -> AssertionError -> 
Expected :seedu.address.model.login.LoginDetails<seedu.address.model.login.UserId@366e2fbbseedu.address.model.login.UserPassword@1655aad4> 
Actual   :seedu.address.model.login.LoginDetails<seedu.address.model.login.UserId@366e2fbbseedu.address.model.login.UserPassword@1655aad4>
Note: There is a whitespace at the end of expected result whereas there isn't any at the end of actual result

Link for cloning my remote repo for debugging purposes: https://github.com/Chocological/addressbook-level4.git

**Comment by ladderinc** [comment]
.equals() method of some of your classes are trying to access private variables with the '.' operator.

**Comment by Chocological** [comment]
Reworked the logic with regards to creating an account. It is able to detect if the user is trying to create an account which already exists in login book.
